#!/usr/bin/env bash
# Regenerate PATCHES.md from the commits carried on top of the upstream base tag.
#
# No commit hashes: they change on every rebase, and the commit that carries this file cannot know
# its own. Rows are the commit subjects, in series order; `git log <base>..main` gives the hashes.
#
# The register is derived from git, never edited by hand: each carried commit must end with an
# Upstream-Status trailer (Pending | Submitted [url] | Backport [#pr] | Denied | Inappropriate [reason]),
# and this script refuses to write the file if one is missing or malformed. The release workflow runs
# it and fails if the checked-in PATCHES.md is stale.
#
# Usage: nexus/gen-patches.sh [base-tag]   (default: nearest upstream v* tag that is not a -nexus tag)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

base=${1:-$(git describe --tags --abbrev=0 --match 'v[0-9]*' --exclude '*-nexus.*' HEAD)}
upstream=https://github.com/FirelyTeam/firely-cql-sdk
base_sha=$(git rev-parse --short=8 "$base^{commit}")
commits=$(git rev-list --reverse "$base..HEAD")
count=$(printf '%s\n' "$commits" | grep -c . || true)

status_re='^(Pending|Submitted \[[^]]+\]|Backport \[[^]]+\]|Denied|Inappropriate \[[^]]+\])$'
{
  echo "# Patches carried by the Nexus EMR fork"
  echo
  echo "Base: [$base]($upstream/releases/tag/$base) (\`$base_sha\`) of [FirelyTeam/firely-cql-sdk]($upstream)."
  echo "Carried: $count commits. Generated by \`nexus/gen-patches.sh\` from the \`Upstream-Status\` trailers; do not edit by hand."
  echo
  echo "Every fix is sent upstream. A row leaves this table when its upstream pull request is merged and the series is rebased onto the release that contains it."
  echo
  echo "| # | subject | upstream status |"
  echo "|---|---|---|"
  n=0
  for c in $commits; do
    n=$((n + 1))
    subject=$(git log -1 --format=%s "$c")
    status=$(git log -1 --format='%(trailers:key=Upstream-Status,valueonly)' "$c" | sed '/^$/d' | head -1)
    if [ -z "$status" ]; then
      echo "error: $c ($subject) has no Upstream-Status trailer" >&2; exit 1
    fi
    if ! printf '%s' "$status" | grep -Eq "$status_re"; then
      echo "error: $c ($subject) has a malformed Upstream-Status: '$status'" >&2; exit 1
    fi
    # [#1234] becomes a link to the upstream pull request
    status=$(printf '%s' "$status" | sed -E "s|\[#([0-9]+)\]|[#\1]($upstream/pull/\1)|g")
    echo "| $n | $subject | $status |"
  done
} > PATCHES.md
echo "PATCHES.md: $count commits on $base"
